spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book
      username: root
      password: 123456


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
       # 开启 mybatis-plus的日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 90



